name: sql_demo
run-name: Setting up the  database
on:
  workflow_dispatch:
    inputs:
      fail-on:
        description:  ""
        required:  true
        default:  "None"
        options:
          -  "None"
          -  "dev"
          -  "test"
          -  "uat"
          -  "prod"
  push:
    branches:
    -  main
  
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment:  dev

    steps:
      -  name:  Checkout  code
         uses:  actions/checkout@v2

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get all changed sql files
        id: changed-sql-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
             **.sql

      - name: List all changed files sql files
        run: |
          for file in ${{ steps.changed-sql-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Get changed SQL files
        id: changed_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- "*.sql" > changed_files.txt
          
      - name: Install the SQL client (e.g., MySQL or PostgreSQL)
        run: |
            sudo apt-get install mysql-client

        env:
          SQL_USER: ${{ secrets.DB_USER }}
          SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SQL_HOST: ${{ secrets.DB_HOST }}
          SQL_PORT: ${{ secrets.DB_PORT }}
          SQL_DATABASE: ${{ secrets.DB_DATABASE }}

      - name: Apply incremental changes
        run: |
          while read -r file; do
            if [ -f "$file" ]; then
              cat "$file" | your-sql-client-command
            fi
          done < changed_files.txt

        env:
          SQL_CLIENT: ${{ secrets.DB_CLIENT }}
