name: sql_demo32
run-name: Setting up the database
on:
  workflow_dispatch:
    inputs:
      fail-on:
        description:  ""
        required:  true
        default:  "None"
        options:
          -  "None"
          -  "dev"
          -  "test"
          -  "uat"
          -  "prod"
  push:
    branches:
    -  test2
  
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment:  dev
    steps:
    - name: Test Output
      run: echo "Here is a test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install MySQL client
      run: |
          sudo apt-get update
          sudo apt-get install mysql-client
      env:
          SQL_USER: ${{ secrets.DB_USER }}
          SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SQL_HOST: ${{ secrets.DB_HOST }}
          SQL_PORT: ${{ secrets.DB_PORT }}
          SQL_DATABASE: ${{ secrets.DB_DATABASE }}

    - name: Find and execute new SQL lines
      run: |
          for file in $(git diff --name-only HEAD~1 HEAD -- "*.sql"); do
            if [ -f "$file" ]; then
              changes=$(git diff HEAD~1..HEAD "$file" | grep "^\+" | sed 's/^\+//')
              echo "$changes" | mysql -u$SQL_USER -p$SQL_PASSWORD -h$SQL_HOST -P$SQL_PORT $SQL_DATABASE
            fi
          done
      env:
          SQL_CLIENT: ${{ secrets.DB_CLIENT }}
        
